import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Messages from '../components/Messages'

export async function getStaticProps(){
  const res = await fetch('https://thiagolp90-laravel-api.herokuapp.com/api/v1/messages')
  const messages = await res.json()
  
  return {
    props: {
      messages
    }
  }
}

interface HomeInterface {
  messages: any;
}

const Home = (props: HomeInterface) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-4">
        <h1 className="text-3xl font-bold underline mb-5">
          Your messages
        </h1>

        <Messages messages={props.messages} />
      </div>
    </>
  )
}
export default Home
